name: dapetduit_admin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6
  flutter_spinkit: ^4.1.1+1
  http: ^0.12.0+4
  flutter_custom_clippers: ^1.1.0
  connectivity: ^0.4.6+2
  pull_to_refresh: ^1.5.7
  random_string: ^2.0.1
  fluttertoast: ^3.1.3
  intl: ^0.16.1
  sqflite: ^1.2.0
  path_provider: ^1.5.1




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  
  assets:
    - images/background.jpeg
  #  - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

